const CIRCLE_RADIUS = 13;
const VISUAL_VIEW_WIDTH = 0.7*window.innerWidth;
const CREATOR_NODE_LEFT = 0.95*VISUAL_VIEW_WIDTH;
const CREATOR_NODE_TOP = 10;
const VISUAL_VIEW_FULL_WIDTH = 1.4*window.innerWidth;
const VISUAL_VIEW_FULL_HEIGHT = 1.5*window.innerHeight;
const SCROLL_THRESHOLD = 40;
const NEW_NODE_LEFT = 0.2*window.innerWidth;
const NEW_NODE_TOP = 0.2*window.innerHeight;

export { CIRCLE_RADIUS, VISUAL_VIEW_WIDTH, CREATOR_NODE_LEFT, 
    CREATOR_NODE_TOP, VISUAL_VIEW_FULL_WIDTH, VISUAL_VIEW_FULL_HEIGHT,
    SCROLL_THRESHOLD, NEW_NODE_LEFT, NEW_NODE_TOP };